#!/usr/bin/env bash

readonly MY_PATH=$(realpath "$0")
# echo "$MY_PATH"
MY_DIR=""
if [[ "$MY_PATH" =~ ^(.*)/[^/]+$ ]]; then
	readonly MY_DIR="${BASH_REMATCH[1]}"
else
	MY_DIR="Failed to get dir"
fi
# echo "$MY_DIR"
declare -r TEST_CASES_PATH="$MY_DIR/decimal_calc_test_cases.txt"

if [ "$1" = '--help' ]; then
	exit 1
elif [ "$1" = '--version' ]; then
	exit 1
fi

declare -r ORIG_IFS="$IFS"
declare -A TESTS=()
do_read() {
	local params=''
	local results=''
	while read -s -t 0; do
		read -sr params results
		# echo "P: $params, R: $results"
		if (( ${#params} <= 0 && ${#results} <= 0 )); then
			break
		elif (( ${#params} <= 0 || ${#results} <= 0 )); then
			continue
		fi
		# if [[ "$params" =~ /$ ]]; then params="${params:0:-1}"; fi
		# if [[ "$results" =~ /$ ]]; then results="${results:0:-1}"; fi
		TESTS[$params]="$results"
	done
	# echo $?
	return
}
IFS=$'>'
do_read < "$TEST_CASES_PATH"
IFS="$ORIG_IFS"
succeeded='true'
for params in "${!TESTS[@]}"; do
	# shellcheck disable=SC2086
	output="$(decimal_calc $params)"
	if [ "$output" != "${TESTS[$params]}" ]; then
		echo "decimal_calc $params: $output != ${TESTS[$params]}" 1>&2
		succeeded='false'
	fi
done

eval $succeeded
exit $?