#!/usr/bin/env bash

show_help() {
	cat << __EOF__
Generates and compresses a man file in the local directory for the given command. Depends on help2man.

Usage: $0 COMMAND [SECTION]
__EOF__
}
show_version() {
	cat << __EOF__
$0 0.1

Copyright (C) 2025 J Mor
__EOF__
}
if [[ "$1" == "--help" ]]; then
	show_help
	exit
elif [[ "$1" == "--version" ]]; then
	show_version
	exit
fi
help2man --section="${2:-1}" "$1" | gzip - >| "./man/man${2:-1}/$1.1.gz"