#!/usr/bin/env bash

if [ "$1" = '--help' ]; then
	exit 1
elif [ "$1" = '--version' ]; then
	exit 1
fi

declare -i columns=$1; shift
declare -i currCol=$1; shift
declare currLine="$1"; shift
declare newChar="$1"; shift
if [ "$newChar" = "${currLine:$currCol:1}" ]; then
	tput setaf 2
else
	tput setaf 1
	if [ "$newChar" = ' ' ]; then
		tput smso
		# newChar+="$(tput rmso)"
		newChar="_$(tput rmso)"
	fi
fi
echo -n "$newChar"
# if [ "$newChar" = ' ' ]; then tput rmso; fi
tput setaf 7
if ((currCol + 1 == columns)); then
	tput cud 2
	echo -n $'\r'
fi