#!/usr/bin/env bash

readonly LOGFILE='/home/jmor/reposLocal/custom-shell-scripts/log.txt'
declare -i current_count=0
# date +'%T %D' >> $LOGFILE
l_exit() {
	# shellcheck disable=SC2086
	# shellcheck disable=SC2317
	echo "Early exit"
	exit 200
}
trap l_exit INT
trap l_exit QUIT
trap l_exit TERM
# trap exit KILL
echo -n $current_count
# echo -n $current_count >>$LOGFILE
while (( current_count < 10 )); do
	sleep 1
	((current_count+=1))
	# echo -n "$current_count"
	if (( current_count & 1 == 1 )); then
		echo -n "$current_count "
		# echo -n "$current_count " >>$LOGFILE
	else
		echo -n "$current_count
"
# 		echo -n "$current_count
# " >>$LOGFILE
	fi
done
# echo $current_count
exit $current_count