#!/usr/bin/env bash

if [ "$1" = '--help' ]; then
	exit 1
elif [ "$1" = '--version' ]; then
	exit 1
fi
##region########################################### GET PATH, DIR, & NAME ###########################################
readonly MY_PATH=$(realpath "$0")
MY_DIR=''
MY_NAME=''
if [[ "$MY_PATH" =~ ^(.*)/([^/]+)$ ]]; then
	readonly MY_DIR="${BASH_REMATCH[1]}" MY_NAME="${BASH_REMATCH[2]}"
else
	readonly MY_DIR="$HOME" MY_NAME="$0"
	echo "$MY_NAME: Failed to get dir" 1>&2
	exit 1
fi
##endregion######################################## GET PATH, DIR, & NAME ###########################################
readonly LOGFILE="$MY_DIR/$MY_NAME.log.txt"
declare -i current_count=0
# date +'%T %D' >> $LOGFILE
l_exit() {
	# shellcheck disable=SC2086
	# shellcheck disable=SC2317
	echo "Early exit"
	exit 200
}
trap l_exit INT
trap l_exit QUIT
trap l_exit TERM
# trap exit KILL
echo -n $current_count
# echo -n $current_count >>$LOGFILE
while (( current_count < 10 )); do
	sleep 1
	((current_count+=1))
	# echo -n "$current_count"
	if (( current_count & 1 == 1 )); then
		echo -n "$current_count "
		# echo -n "$current_count " >>$LOGFILE
	else
		echo -n "$current_count
"
# 		echo -n "$current_count
# " >>$LOGFILE
	fi
done
# echo $current_count
exit $current_count