#!/usr/bin/env bash

# term_size2 - Dynamically display terminal window size

if [ "$1" = '--help' ]; then
	exit 1
elif [ "$1" = '--version' ]; then
	exit 1
fi

readonly ORIG_IFS=$IFS
current_count=0

# display_count() {
# 	tput smcup
# 	tput sc
# 	tput 
# }
init_row_col=($(./cursor_pos))
exec 3< <("$@")
val="$(<(&3))"
line=""
out_pipe() {
	echo -n "$(<(&3))"
}
while :;do
	line=$(out_pipe)
	let current_count+=1
	echo -n $current_count
	sleep 1
done
exit $?